pipeline {
  agent any
  stages {
    stage('SonarQube analysis') {
      steps {
        withSonarQubeEnv('SonarQube_LATEST') {
          script {
            def scannerHome = tool 'SonarQubeScannerCLI';
            def nodeHome = tool 'NodeJS';
            sh "${scannerHome}/bin/sonar-scanner -Dsonar.nodejs.executable=${nodeHome}/bin/node"
          }
        }
      }
    }
  }
}
